site_name: k0rdent Enterprise Images
site_description: Documentation for k0rdent Enterprise Images.
site_author: Mirantis, Inc.

docs_dir: docs/
repo_name: k0rdent/kcm
repo_url: https://github.com/k0rdent/kcm
edit_uri: https://github.com/k0rdent/docs/edit/main/docs/

copyright:
  Copyright &copy; 2025 The k0rdent authors | Documentation distributed under <a href="https://creativecommons.org/licenses/by/4.0/legalcode.txt">CC-BY-4.0</a>.

theme:
  name: "material"
  highlightjs: true
  language: "en"
  custom_dir: docs/custom_theme

  favicon: img/k0rdent-logo-mark-inverted.svg
  logo: img/k0rdent-logo-horizontal-inverted.svg

  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
    - scheme: slate
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
  features:
    - toc.autohide
    - search.suggest
    - search.highlight
    - content.code.copy
    - navigation.tracking   # Anchor tracking
    - toc.follow            # Sidebar is automatically scrolled so that the active anchor is always visible
    - search.suggest        # Search suggestions
    - search.highlight      # Search highlights all occurrences after following the link
    - content.action.edit
    - content.action.view
    - navigation.path       # Not working, for sponsors only
    - navigation.indexes
    # - navigation.tabs
    # - navigation.tabs.sticky

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascripts/feedback.js
  - javascripts/plausible.js

plugins:
  - search
  - ezglossary:
      section_config:
        - name: demo
          inline_refs: short
  - macros:
      j2_variable_start_string: "{{{"
      j2_variable_end_string: "}}}"
  - exclude:
      glob:
        - "*.etag"
        - Dockerfile.serve-dev
        - Makefile*
        - requirements_pip.txt
        - requirements.txt
  - include-markdown

nav:
  - AWS AMI Image: aws-ami.md

markdown_extensions:
  - callouts
  - tables
  - pymdownx.details
  - md_in_html
  - attr_list # .. to support images attrs like { width="150" }
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.superfences: {}
  - pymdownx.inlinehilite: {}
  - pymdownx.snippets: {}
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tabbed:
      alternate_style: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - toc:
      permalink: "#"
  - def_list

extra:
  docs_repo_name: k0rdent/docs
  repo_url: https://github.com/k0rdent/kcm
  generator: false
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/k0rdent/kcm
      name: k0rdent on GitHub
    - icon: fontawesome/brands/x-twitter
      link: https://x.com/k0rdent
      name: k0rdent on X
    - icon: fontawesome/brands/bluesky
      link: https://bsky.app/profile/k0rdent.bsky.social
      name: k0rdent on BlueSky
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/channel/UChXQ6kbvjnAtdZAQpl7Fo4A
      name: k0rdent on YouTube
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/k0rdent/
      name: k0rdent on LinkedIn
  version:
    provider: mike
    default: stable
