name: Deploy MkDocs to GitHub Pages

on:
  push:
    branches:
      - '**'
    paths:
      - mkdocs.yml
      - docs/**
      - scripts/deploy_web.sh
      - .github/workflows/gh-pages-deploy.yml

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Configure Git User
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Test web pages build
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          echo "REPO: $GITHUB_CONTEXT"
          mkdocs build

      - name: Build and Deploy pages
        run: |
          SITE_URL=${{ vars.SITE_URL }} ./scripts/deploy_web.sh
